### Send POST request to start a batch job
POST http://localhost:8080/dmit2015-batch-demo-1.0-SNAPSHOT/webapi/batch-jobs/job

### Check the batch job status for id 1
GET http://localhost:8080/dmit2015-batch-demo-1.0-SNAPSHOT/webapi/batch-jobs/1

### Send request for number of EnforcementZoneCentre objects
GET http://localhost:8080/dmit2015-batch-demo-1.0-SNAPSHOT/webapi/EnforcementZoneCentres/count

### Send request for EnforcementZoneCentre with siteId of 2202
GET http://localhost:8080/dmit2015-batch-demo-1.0-SNAPSHOT/webapi/EnforcementZoneCentres/2202

### Send request for all of EnforcementZoneCentre objects
GET http://localhost:8080/dmit2015-batch-demo-1.0-SNAPSHOT/webapi/EnforcementZoneCentres